package com.selrahc13.moderndecorations.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.tileentity.TileEntity;

//Date: 2/1/2015 9:55:42 PM
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX







public class ModelWideSign extends ModelBase
{
//fields
 ModelRenderer Sign1;
 
public ModelWideSign()
{
 textureWidth = 64;
 textureHeight = 32;
 
   Sign1 = new ModelRenderer(this, 0, -24);
   Sign1.addBox(0F, 0F, 0F, 0, 16, 24);
   Sign1.setRotationPoint(-12F, 0F, 2.1F);
   Sign1.setTextureSize(64, 32);
   Sign1.mirror = true;
   setRotation(Sign1, 0F, 1.570796F, 0F);
}

public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
{
 super.render(entity, f, f1, f2, f3, f4, f5);
 setRotationAngles(f, f1, f2, f3, f4, f5);
 Sign1.render(f5);
}

public void render(TileEntity te, float f) {

	float f5 = 0.0625F;
	setRotationAngles(te, f);
	Sign1.render(f5);
}

private void setRotation(ModelRenderer model, float x, float y, float z)
{
 model.rotateAngleX = x;
 model.rotateAngleY = y;
 model.rotateAngleZ = z;
}

public void setRotationAngles(TileEntity te, float f) {
	super.setRotationAngles(0f, 0f, 0f, 0f, 0f, f, null);
}

public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
{
 super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
}

}
