package com.selrahc13.moderndecorations.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.tileentity.TileEntity;

//Date: 2/1/2015 9:55:42 PM
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX







public class ModelDoublePost extends ModelBase
{
//fields
 ModelRenderer Post1;
 ModelRenderer Post2;

public ModelDoublePost()
{
 textureWidth = 64;
 textureHeight = 32;
 
   Post1 = new ModelRenderer(this, 0, 0);
   Post1.addBox(0F, 0F, 0F, 4, 16, 4);
   Post1.setRotationPoint(-7F, 8F, -2F);
   Post1.setTextureSize(64, 32);
   Post1.mirror = true;
   setRotation(Post1, 0F, 0F, 0F);
   Post2 = new ModelRenderer(this, 0, 0);
   Post2.addBox(0F, 0F, 0F, 4, 16, 4);
   Post2.setRotationPoint(3F, 8F, -2F);
   Post2.setTextureSize(64, 32);
   Post2.mirror = true;
   setRotation(Post2, 0F, 0F, 0F);
}

public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
{
 super.render(entity, f, f1, f2, f3, f4, f5);
 setRotationAngles(f, f1, f2, f3, f4, f5);
 Post1.render(f5);
 Post2.render(f5);
}

public void render(TileEntity te, float f) {

	float f5 = 0.0625F;
	setRotationAngles(te, f);
	Post1.render(f5);
	Post2.render(f5);
}

private void setRotation(ModelRenderer model, float x, float y, float z)
{
 model.rotateAngleX = x;
 model.rotateAngleY = y;
 model.rotateAngleZ = z;
}

public void setRotationAngles(TileEntity te, float f) {
	super.setRotationAngles(0f, 0f, 0f, 0f, 0f, f, null);
}

public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
{
 super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
}

}
